Skios 109 backend feed mutations
skiosa/core-service pull request #20
Opened 2022-04-20 21:25 UTC by DrShadowPLay

# Skiosa - PR
- [ ] added test(s), or explain why one is not needed/possible...
- [ ] added comments to all the functions
- [ ] added documentation to latex project
- [ ] code can't be split up into smaller logical units
- [x] code is formated and linted

2022-04-20 21:30 UTC, eintim approved these changes

2022-04-21 10:43 UTC, eintim requested changes
Input validation and documentation is missing

2022-04-25 12:23 UTC, LukasLJL commented
pls add documentation

2022-04-26 19:37 UTC, LukasLJL approved these changes
lgtm :D

2022-04-26 19:45 UTC, merged